package com.arcsoft.studyOnline.dao;

import com.arcsoft.studyOnline.bean.Audios;
import com.arcsoft.studyOnline.bean.AudiosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AudiosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audios
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    long countByExample(AudiosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audios
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    int deleteByExample(AudiosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audios
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    int insert(Audios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audios
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    int insertSelective(Audios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audios
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    List<Audios> selectByExample(AudiosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audios
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") Audios record, @Param("example") AudiosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audios
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    int updateByExample(@Param("record") Audios record, @Param("example") AudiosExample example);
}