package com.arcsoft.studyOnline.dao;

import com.arcsoft.studyOnline.bean.Discuss;
import com.arcsoft.studyOnline.bean.DiscussExample;
import java.util.Date;
import java.util.List;

import com.arcsoft.studyOnline.bean.DiscussWithEmpName;
import org.apache.ibatis.annotations.Param;

public interface DiscussMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    long countByExample(DiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    int deleteByExample(DiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    int insert(Discuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    int insertSelective(Discuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    List<Discuss> selectByExampleWithBLOBs(DiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    List<Discuss> selectByExample(DiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    int updateByExampleSelective(@Param("record") Discuss record, @Param("example") DiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Discuss record, @Param("example") DiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    int updateByExample(@Param("record") Discuss record, @Param("example") DiscussExample example);

    void insertDiscuss(@Param("videoId")Integer videoId,@Param("empId") Integer empId,@Param("content") String content,@Param("date") Date date,@Param("preId") Integer preId);

    List<DiscussWithEmpName> selectDiscussListByVideoId(@Param("videoId")Integer videoId);
}