package com.arcsoft.studyOnline.dao;

import com.arcsoft.studyOnline.bean.PrivateMessage;
import com.arcsoft.studyOnline.bean.PrivateMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrivateMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_message
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    long countByExample(PrivateMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_message
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    int deleteByExample(PrivateMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_message
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    int insert(PrivateMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_message
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    int insertSelective(PrivateMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_message
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    List<PrivateMessage> selectByExample(PrivateMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_message
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    int updateByExampleSelective(@Param("record") PrivateMessage record, @Param("example") PrivateMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_message
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    int updateByExample(@Param("record") PrivateMessage record, @Param("example") PrivateMessageExample example);
}