package com.arcsoft.studyOnline.dao;

import com.arcsoft.studyOnline.bean.VideoSort;
import com.arcsoft.studyOnline.bean.VideoSortExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoSortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sort
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    long countByExample(VideoSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sort
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    int deleteByExample(VideoSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sort
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    int insert(VideoSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sort
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    int insertSelective(VideoSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sort
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    List<VideoSort> selectByExample(VideoSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sort
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") VideoSort record, @Param("example") VideoSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_sort
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    int updateByExample(@Param("record") VideoSort record, @Param("example") VideoSortExample example);
}