package com.arcsoft.studyOnline.dao;

import com.arcsoft.studyOnline.bean.ViewRecord;
import com.arcsoft.studyOnline.bean.ViewRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ViewRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_record
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    long countByExample(ViewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_record
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    int deleteByExample(ViewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_record
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    int insert(ViewRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_record
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    int insertSelective(ViewRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_record
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    List<ViewRecord> selectByExample(ViewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_record
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") ViewRecord record, @Param("example") ViewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_record
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    int updateByExample(@Param("record") ViewRecord record, @Param("example") ViewRecordExample example);
}