package com.arcsoft.studyOnline.bean;

public class Adminstrator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminstrator.id
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminstrator.username
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminstrator.password
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminstrator.id
     *
     * @return the value of adminstrator.id
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminstrator.id
     *
     * @param id the value for adminstrator.id
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminstrator.username
     *
     * @return the value of adminstrator.username
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminstrator.username
     *
     * @param username the value for adminstrator.username
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminstrator.password
     *
     * @return the value of adminstrator.password
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminstrator.password
     *
     * @param password the value for adminstrator.password
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}