package com.arcsoft.studyOnline.bean;

public class Audios {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audios.id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audios.name
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audios.path
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audios.length
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    private String length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audios.route_id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    private Integer routeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audios.id
     *
     * @return the value of audios.id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audios.id
     *
     * @param id the value for audios.id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audios.name
     *
     * @return the value of audios.name
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audios.name
     *
     * @param name the value for audios.name
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audios.path
     *
     * @return the value of audios.path
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audios.path
     *
     * @param path the value for audios.path
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audios.length
     *
     * @return the value of audios.length
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public String getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audios.length
     *
     * @param length the value for audios.length
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public void setLength(String length) {
        this.length = length == null ? null : length.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audios.route_id
     *
     * @return the value of audios.route_id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public Integer getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audios.route_id
     *
     * @param routeId the value for audios.route_id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }
}