package com.arcsoft.studyOnline.bean;

import com.arcsoft.studyOnline.utils.JsonDateSerializer;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Discuss {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss.id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss.vedio_id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    private Integer vedioId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss.commentators_id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    private Integer commentatorsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss.time
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss.pre_id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    private Integer preId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss.from_who
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    private Integer fromWho;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss.content
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.id
     *
     * @return the value of discuss.id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.id
     *
     * @param id the value for discuss.id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.vedio_id
     *
     * @return the value of discuss.vedio_id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public Integer getVedioId() {
        return vedioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.vedio_id
     *
     * @param vedioId the value for discuss.vedio_id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public void setVedioId(Integer vedioId) {
        this.vedioId = vedioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.commentators_id
     *
     * @return the value of discuss.commentators_id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public Integer getCommentatorsId() {
        return commentatorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.commentators_id
     *
     * @param commentatorsId the value for discuss.commentators_id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public void setCommentatorsId(Integer commentatorsId) {
        this.commentatorsId = commentatorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.time
     *
     * @return the value of discuss.time
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonSerialize(using=JsonDateSerializer.class)
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.time
     *
     * @param time the value for discuss.time
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.pre_id
     *
     * @return the value of discuss.pre_id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public Integer getPreId() {
        return preId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.pre_id
     *
     * @param preId the value for discuss.pre_id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public void setPreId(Integer preId) {
        this.preId = preId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.from_who
     *
     * @return the value of discuss.from_who
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public Integer getFromWho() {
        return fromWho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.from_who
     *
     * @param fromWho the value for discuss.from_who
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public void setFromWho(Integer fromWho) {
        this.fromWho = fromWho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.content
     *
     * @return the value of discuss.content
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.content
     *
     * @param content the value for discuss.content
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}