package com.arcsoft.studyOnline.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DiscussExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table discuss
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table discuss
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table discuss
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    public DiscussExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table discuss
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVedioIdIsNull() {
            addCriterion("vedio_id is null");
            return (Criteria) this;
        }

        public Criteria andVedioIdIsNotNull() {
            addCriterion("vedio_id is not null");
            return (Criteria) this;
        }

        public Criteria andVedioIdEqualTo(Integer value) {
            addCriterion("vedio_id =", value, "vedioId");
            return (Criteria) this;
        }

        public Criteria andVedioIdNotEqualTo(Integer value) {
            addCriterion("vedio_id <>", value, "vedioId");
            return (Criteria) this;
        }

        public Criteria andVedioIdGreaterThan(Integer value) {
            addCriterion("vedio_id >", value, "vedioId");
            return (Criteria) this;
        }

        public Criteria andVedioIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vedio_id >=", value, "vedioId");
            return (Criteria) this;
        }

        public Criteria andVedioIdLessThan(Integer value) {
            addCriterion("vedio_id <", value, "vedioId");
            return (Criteria) this;
        }

        public Criteria andVedioIdLessThanOrEqualTo(Integer value) {
            addCriterion("vedio_id <=", value, "vedioId");
            return (Criteria) this;
        }

        public Criteria andVedioIdIn(List<Integer> values) {
            addCriterion("vedio_id in", values, "vedioId");
            return (Criteria) this;
        }

        public Criteria andVedioIdNotIn(List<Integer> values) {
            addCriterion("vedio_id not in", values, "vedioId");
            return (Criteria) this;
        }

        public Criteria andVedioIdBetween(Integer value1, Integer value2) {
            addCriterion("vedio_id between", value1, value2, "vedioId");
            return (Criteria) this;
        }

        public Criteria andVedioIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vedio_id not between", value1, value2, "vedioId");
            return (Criteria) this;
        }

        public Criteria andCommentatorsIdIsNull() {
            addCriterion("commentators_id is null");
            return (Criteria) this;
        }

        public Criteria andCommentatorsIdIsNotNull() {
            addCriterion("commentators_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommentatorsIdEqualTo(Integer value) {
            addCriterion("commentators_id =", value, "commentatorsId");
            return (Criteria) this;
        }

        public Criteria andCommentatorsIdNotEqualTo(Integer value) {
            addCriterion("commentators_id <>", value, "commentatorsId");
            return (Criteria) this;
        }

        public Criteria andCommentatorsIdGreaterThan(Integer value) {
            addCriterion("commentators_id >", value, "commentatorsId");
            return (Criteria) this;
        }

        public Criteria andCommentatorsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("commentators_id >=", value, "commentatorsId");
            return (Criteria) this;
        }

        public Criteria andCommentatorsIdLessThan(Integer value) {
            addCriterion("commentators_id <", value, "commentatorsId");
            return (Criteria) this;
        }

        public Criteria andCommentatorsIdLessThanOrEqualTo(Integer value) {
            addCriterion("commentators_id <=", value, "commentatorsId");
            return (Criteria) this;
        }

        public Criteria andCommentatorsIdIn(List<Integer> values) {
            addCriterion("commentators_id in", values, "commentatorsId");
            return (Criteria) this;
        }

        public Criteria andCommentatorsIdNotIn(List<Integer> values) {
            addCriterion("commentators_id not in", values, "commentatorsId");
            return (Criteria) this;
        }

        public Criteria andCommentatorsIdBetween(Integer value1, Integer value2) {
            addCriterion("commentators_id between", value1, value2, "commentatorsId");
            return (Criteria) this;
        }

        public Criteria andCommentatorsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("commentators_id not between", value1, value2, "commentatorsId");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Date value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Date value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Date value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Date value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Date value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Date> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Date> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Date value1, Date value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Date value1, Date value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andPreIdIsNull() {
            addCriterion("pre_id is null");
            return (Criteria) this;
        }

        public Criteria andPreIdIsNotNull() {
            addCriterion("pre_id is not null");
            return (Criteria) this;
        }

        public Criteria andPreIdEqualTo(Integer value) {
            addCriterion("pre_id =", value, "preId");
            return (Criteria) this;
        }

        public Criteria andPreIdNotEqualTo(Integer value) {
            addCriterion("pre_id <>", value, "preId");
            return (Criteria) this;
        }

        public Criteria andPreIdGreaterThan(Integer value) {
            addCriterion("pre_id >", value, "preId");
            return (Criteria) this;
        }

        public Criteria andPreIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("pre_id >=", value, "preId");
            return (Criteria) this;
        }

        public Criteria andPreIdLessThan(Integer value) {
            addCriterion("pre_id <", value, "preId");
            return (Criteria) this;
        }

        public Criteria andPreIdLessThanOrEqualTo(Integer value) {
            addCriterion("pre_id <=", value, "preId");
            return (Criteria) this;
        }

        public Criteria andPreIdIn(List<Integer> values) {
            addCriterion("pre_id in", values, "preId");
            return (Criteria) this;
        }

        public Criteria andPreIdNotIn(List<Integer> values) {
            addCriterion("pre_id not in", values, "preId");
            return (Criteria) this;
        }

        public Criteria andPreIdBetween(Integer value1, Integer value2) {
            addCriterion("pre_id between", value1, value2, "preId");
            return (Criteria) this;
        }

        public Criteria andPreIdNotBetween(Integer value1, Integer value2) {
            addCriterion("pre_id not between", value1, value2, "preId");
            return (Criteria) this;
        }

        public Criteria andFromWhoIsNull() {
            addCriterion("from_who is null");
            return (Criteria) this;
        }

        public Criteria andFromWhoIsNotNull() {
            addCriterion("from_who is not null");
            return (Criteria) this;
        }

        public Criteria andFromWhoEqualTo(Integer value) {
            addCriterion("from_who =", value, "fromWho");
            return (Criteria) this;
        }

        public Criteria andFromWhoNotEqualTo(Integer value) {
            addCriterion("from_who <>", value, "fromWho");
            return (Criteria) this;
        }

        public Criteria andFromWhoGreaterThan(Integer value) {
            addCriterion("from_who >", value, "fromWho");
            return (Criteria) this;
        }

        public Criteria andFromWhoGreaterThanOrEqualTo(Integer value) {
            addCriterion("from_who >=", value, "fromWho");
            return (Criteria) this;
        }

        public Criteria andFromWhoLessThan(Integer value) {
            addCriterion("from_who <", value, "fromWho");
            return (Criteria) this;
        }

        public Criteria andFromWhoLessThanOrEqualTo(Integer value) {
            addCriterion("from_who <=", value, "fromWho");
            return (Criteria) this;
        }

        public Criteria andFromWhoIn(List<Integer> values) {
            addCriterion("from_who in", values, "fromWho");
            return (Criteria) this;
        }

        public Criteria andFromWhoNotIn(List<Integer> values) {
            addCriterion("from_who not in", values, "fromWho");
            return (Criteria) this;
        }

        public Criteria andFromWhoBetween(Integer value1, Integer value2) {
            addCriterion("from_who between", value1, value2, "fromWho");
            return (Criteria) this;
        }

        public Criteria andFromWhoNotBetween(Integer value1, Integer value2) {
            addCriterion("from_who not between", value1, value2, "fromWho");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table discuss
     *
     * @mbg.generated do_not_delete_during_merge Tue May 23 18:58:33 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table discuss
     *
     * @mbg.generated Tue May 23 18:58:33 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}