package com.arcsoft.studyOnline.bean;

public class Position {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.id
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.name
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.premission_level
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    private Integer premissionLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.id
     *
     * @return the value of position.id
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.id
     *
     * @param id the value for position.id
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.name
     *
     * @return the value of position.name
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.name
     *
     * @param name the value for position.name
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.premission_level
     *
     * @return the value of position.premission_level
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    public Integer getPremissionLevel() {
        return premissionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.premission_level
     *
     * @param premissionLevel the value for position.premission_level
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    public void setPremissionLevel(Integer premissionLevel) {
        this.premissionLevel = premissionLevel;
    }
}