package com.arcsoft.studyOnline.bean;

import java.util.Date;

public class Route {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.lesson_id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    private Integer lessonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.route_name
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    private String routeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.time
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.id
     *
     * @return the value of route.id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.id
     *
     * @param id the value for route.id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.lesson_id
     *
     * @return the value of route.lesson_id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public Integer getLessonId() {
        return lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.lesson_id
     *
     * @param lessonId the value for route.lesson_id
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public void setLessonId(Integer lessonId) {
        this.lessonId = lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.route_name
     *
     * @return the value of route.route_name
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public String getRouteName() {
        return routeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.route_name
     *
     * @param routeName the value for route.route_name
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public void setRouteName(String routeName) {
        this.routeName = routeName == null ? null : routeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.time
     *
     * @return the value of route.time
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.time
     *
     * @param time the value for route.time
     *
     * @mbg.generated Sun Jun 18 17:34:40 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }
}