package com.arcsoft.studyOnline.bean;

public class VideoSort {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sort.id
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_sort.name
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sort.id
     *
     * @return the value of video_sort.id
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sort.id
     *
     * @param id the value for video_sort.id
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_sort.name
     *
     * @return the value of video_sort.name
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_sort.name
     *
     * @param name the value for video_sort.name
     *
     * @mbg.generated Tue May 23 22:25:57 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}